### PR TITLE
turn files into cljc

### PR DESCRIPTION
**Pull request by wilkerlucio**

### CODE REVIEW

**Comment by paraseba** [comment]
thank you!

**Comment by wilkerlucio** [comment]
Thanks for reacting so quickly :)

Can you please release a new version with it?

**Comment by paraseba** [comment]
@wilkerlucio i'll push a new release as soon as I get a reset password email from clojars. It's failing for some reason, already reported it.

Thanks

**Comment by paraseba** [comment]
@wilkerlucio : done, give [faker "0.3.2"] a try please. Thanks for the PR!

**Comment by wilkerlucio** [comment]
nice, thanks!

**Pull request merged**
